### ISSUE TITLE
semantic-map -- limit bounding box of basemap (openlayers)

### ISSUE THREAD

**Issue by lklic** [researchspace/researchspace#137]
config option to add ability to set min and max zoom levels for layers:
https://openlayers.org/en/latest/examples/layer-zoom-limits.html

**Comment by lklic** [comment]
awaiting PR

**Comment by RemoGrillo** [comment]
Allow these OPTIONAL possibilities, as template props:

- [ ] fixed center (providing a center point and a zoom level)
- [ ] fixed bounding box (providing 4 points)

these above if set will overwrite the center to features functionality.

Also these possibilities:
- [ ] limit bounding box (by default it zooms to loaded features unless otherwise specified but doesn't allow going outside a provided bounding box of 4 points)
- [ ] disable movement control in general
